In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [ ]:
a=pd.read_csv(r'C:\Users\DELL\Downloads\data (1).csv')

In [ ]:
a.head()

Jaundice\nRenal failure (kidney damage)\nPulmonary hemorrhage\nCardiac arrhythmias\nPneumonitis\nSeptic shock  \
0                                                  1                                                               
1                                                  0                                                               
2                                                  0                                                               
3                                                  0                                                               
4                                                  0                                                               

   devloped after strep throat bacteria called group A streptocoaus  \
0                                                  0                  
1                                                  1                  
2                                                  0                  
3                                                  0                  
4                                                  0                  

   Bacterium Bartonella quintana  \
0                              0   
1                              0   
2                              1   
3                              0   
4                              0   

   Orientia tsutsugamushi bacteria,through bites of infected chiggers  \
0                                                  0                    
1                                                  0                    
2                                                  0                    
3                                                  1                    
4                                                  0                    

   Streptococcus  Rickettsia  Strain of haemophilus biogroupmagyptius  F  \
0              0           0                                        0  1   
1              0           0                                        0  1   
2              0           0                                        0  1   
3              0           0                                        0  1   
4              1           0                                        0  1   

   100.5–102.2  102.2–104.0  ...  jaundice  Retro-orbital  Radish eys  \
0            1            0  ...         1              1           1   
1            1            0  ...         0              0           0   
2            0            0  ...         0              1           0   
3            0            0  ...         0              0           0   
4            1            0  ...         0              0           0   

   Abdominal pain  Abdominal pain sevrer  comma  Septic Shock  death  \
0               1                      0      0             1      1   
1               0                      0      0             0      0   
2               1                      0      0             0      0   
3               0                      0      1             0      0   
4               1                      0      0             0      0   

   diagnosis  Fever  
0          0      1  
1          0      0  
2          0      1  
3          0      0  
4          0      1  

[5 rows x 45 columns]

In [ ]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 45 columns):
 #   Column                                                                                                    Non-Null Count  Dtype
---  ------                                                                                                    --------------  -----
 0   Jaundice
Renal failure (kidney damage)
Pulmonary hemorrhage
Cardiac arrhythmias
Pneumonitis
Septic shock  62 non-null     int64
 1   devloped after strep throat bacteria called group A streptocoaus                                          62 non-null     int64
 2   Bacterium Bartonella quintana                                                                             62 non-null     int64
 3   Orientia tsutsugamushi bacteria,through bites of infected chiggers                                        62 non-null     int64
 4   Streptococcus                                                                                 

In [ ]:
a.columns

Index(['Jaundice\nRenal failure (kidney damage)\nPulmonary hemorrhage\nCardiac arrhythmias\nPneumonitis\nSeptic shock',
       'devloped after strep throat bacteria called group A streptocoaus',
       'Bacterium Bartonella quintana',
       'Orientia tsutsugamushi bacteria,through bites of infected chiggers',
       'Streptococcus', 'Rickettsia',
       'Strain of haemophilus biogroupmagyptius', 'F', '100.5–102.2',
       '102.2–104.0', '104.1–106.0', 'Acute <7days', 'Subacute < = 2 weeks',
       'Cronic >2weeks', 'Fatigue', 'Weakness Fatek', 'Muscle pain',
       'painful tender joints ', 'heart faliur shortemess of breath',
       'Body ache', 'Headache', '1 Headache (with pain behind the e1)',
       '1 Splitting headache', 'Sore throa', '1 swollen gland in neck',
       'cough', 'Vomiting', 'Diarrhoea', 'Rash', 'Pink ring with clear center',
       ' Truncal',
       ' Red skin strawberry toungh  ,bright red skin under elbow and groin ',
       'Rose color spots ', 'Nausea', 'Chi

In [ ]:
x=a.drop(['Jaundice\nRenal failure (kidney damage)\nPulmonary hemorrhage\nCardiac arrhythmias\nPneumonitis\nSeptic shock'], axis=1)
y=a['Jaundice\nRenal failure (kidney damage)\nPulmonary hemorrhage\nCardiac arrhythmias\nPneumonitis\nSeptic shock']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)

In [ ]:
x_test.shape

(19, 44)

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
b=LogisticRegression()

In [ ]:
b.fit(x_train,y_train)

LogisticRegression()

In [ ]:
y_pred=b.predict(x_test)

In [ ]:
y_test.head()

54    0
60    0
30    0
44    0
46    0
Name: Jaundice\nRenal failure (kidney damage)\nPulmonary hemorrhage\nCardiac arrhythmias\nPneumonitis\nSeptic shock, dtype: int64

In [ ]:
y_pred[0:5]

array([0, 0, 0, 0, 0], dtype=int64)

In [ ]:
from sklearn.metrics import mean_squared_error

In [ ]:
mean_squared_error(y_test,y_pred)

0.10526315789473684

In [ ]:
b.score(x_train,y_train)

0.9534883720930233

In [ ]:
b.intercept_

array([-1.48900738])

In [ ]:
b.coef_

array([[-0.53096187, -0.28911179, -0.30336825,  0.14051979, -0.6344789 ,
         0.73866892, -0.17925964, -0.12605369, -0.16583906,  0.68741266,
        -0.13284772, -0.7163307 , -0.4392035 , -0.05763085, -0.26353003,
        -0.06316424, -0.13125356,  0.26303657, -0.65757938, -0.09004494,
        -0.55045993,  0.39690736, -0.43781609,  0.35812326,  0.06398517,
         0.28259475,  0.41822569, -0.16088875, -0.57009874, -0.31231605,
        -0.35151825,  0.03575134, -0.19223478, -0.23662304,  0.96146663,
         0.07436538,  0.26566109, -0.15595652, -0.11640826, -0.15301573,
         0.42016543,  0.49848657, -0.24921718,  0.1521298 ]])

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
# Evaluating the Algorithm
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))  
print('\nMean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('\nRoot Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print("\nConfusion Metrics Of Our Test Dataset is\n", cm)

Mean Absolute Error: 0.10526315789473684

Mean Squared Error: 0.10526315789473684

Root Mean Squared Error: 0.3244428422615251

Confusion Metrics Of Our Test Dataset is
 [[17  0]
 [ 2  0]]


In [ ]:
x_new=[[0,0,1,0,1,0,1,0,0,1,0,1,0,0,1,1,1,0,0,0,0,0,0,1,1,1,1,0,1,0,1,0,1,0,1,0,1,0,0,0,0,0,1,1]]

In [ ]:
y_pred=b.predict(x_new)

In [ ]:
y_pred

array([0], dtype=int64)